apiVersion: v2
description: Observability stack Kyverno policies
name: observability-policies
version: 0.0.3
appVersion: 0.0.1
home: https://github.com/giantswarm/observability-policies
icon: https://s.giantswarm.io/app-icons/kyverno/1/light.svg
annotations:
  io.giantswarm.application.team: atlas
keywords:
  - monitoring
type: application
